run:
  timeout: 1m
  build-tags:
    - wireinject
linters:
  enable-all: true
  disable:
    # turn on later
    - godox
    # deprecated
    - tenv
    # not relevant
    - varnamelen
    - wrapcheck
    - paralleltest
    - exhaustruct
linters-settings:
  lll:
    line-length: 140
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/bavix)
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
issues:
  exclude-files:
    - pkg/deps/builder.go
  exclude-dirs:
    - example
  exclude-rules:
    - path: cmd/*
      linters:
        - gochecknoglobals
        - gochecknoinits
    - path: (.+)_test.go
      linters:
        - dupl