version: "2"
run:
  build-tags:
    - wireinject
linters:
  default: all
  disable:
    - exhaustruct
    - godox
    - paralleltest
    - varnamelen
    - wrapcheck
    - funcorder
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com
            - google.golang.org
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: cmd/*
      - linters:
          - dupl
          - lll
        path: (.+)_test.go
    paths:
      - example
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/bavix)
  exclusions:
    generated: lax
    paths:
      - example
      - third_party$
      - builtin$
      - examples$
