version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686"
      - "4317:4317" # grpc
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
