name: build app

on:
  pull_request:
    branches: [ master ]

jobs:
  docs:
    permissions:
      contents: write
    uses: bavix/.github/.github/workflows/compile-assets.yml@0.2.4
    secrets: inherit