name: Continuous Integration
on:
  pull_request:

jobs:
  test-and-coverage:
    name: "Unit + E2E Tests (Coverage)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true

      - name: Set up cache for dependencies
        uses: actions/cache@v4
        with:
          path: |
            grpcurl
            grpctestify.sh
          key: deps-cache-${{ runner.os }}-v1

      - name: Install dependencies
        run: |
          if ! which jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

          if [ ! -f grpcurl ]; then
            curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz" | tar -xz
            chmod +x grpcurl
          fi
          echo "$(pwd)" >> $GITHUB_PATH

          if [ ! -f grpctestify.sh ]; then
            curl -sSL https://raw.githubusercontent.com/gripmock/grpctestify/v0.0.8/grpctestify.sh -o grpctestify.sh
            chmod +x grpctestify.sh
          fi

      - name: Run unit tests with coverage
        run: |
          mkdir -p /tmp/cover-unit
          GOCOVERDIR=/tmp/cover-unit go test -cover ./...
        shell: bash

      - name: Build GripMock Server with coverage
        run: |
          mkdir -p /tmp/cover-e2e
          GOCOVERDIR=/tmp/cover-e2e go build -cover -o /tmp/gripmock .
          chmod +x /tmp/gripmock

      - name: Start GripMock Server
        run: |
          find . -name "*.proto.src" -type f -delete
          GOCOVERDIR=/tmp/cover-e2e /tmp/gripmock --stub=examples examples &
          echo $! > /tmp/gripmock.pid

      - name: Run gripmock check with coverage
        run: |
          mkdir -p /tmp/cover-check
          GOCOVERDIR=/tmp/cover-check /tmp/gripmock check --timeout=60s --silent

      - name: Run examples
        run: |
          ./grpctestify.sh examples/

      - name: Stop GripMock Server gracefully
        run: |
          kill -INT $(cat /tmp/gripmock.pid) || true
          sleep 5
          rm /tmp/gripmock.pid || true

      - name: Merge all coverage data
        run: |
          mkdir -p /tmp/cover-all
          go tool covdata merge \
            -i=/tmp/cover-unit,/tmp/cover-e2e,/tmp/cover-check \
            -o=/tmp/cover-all

      - name: Generate coverage report
        run: |
          go tool covdata textfmt -i=/tmp/cover-all -o coverage.txt
          go tool covdata percent -i=/tmp/cover-all

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.txt

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage.txt:lcov

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.txt
