name: End-to-End
on:
  pull_request:

jobs:
  e2e:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up cache for dependencies
        uses: actions/cache@v4
        with:
          path: |
            grpcurl
            grpctestify.sh
          key: deps-cache-${{ runner.os }}-v1

      - name: Build Docker image with BuildKit
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --progress=plain \
            --cache-from type=gha,scope=e2e \
            --cache-to type=gha,mode=max,scope=e2e \
            -t gripmock-server-local .

      - name: Install dependencies
        run: |
          if ! which jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

          if [ ! -f grpcurl ]; then
            curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz" | tar -xz
            chmod +x grpcurl
          fi
          echo "$(pwd)" >> $GITHUB_PATH

          if [ ! -f grpctestify.sh ]; then
            curl -sSL https://raw.githubusercontent.com/gripmock/grpctestify/v0.0.8/grpctestify.sh -o grpctestify.sh
            chmod +x grpctestify.sh
          fi

      - name: Start GripMock Server
        run: |
          docker run -d --name gripmock-server \
            -v ./examples:/proto \
            -v ./examples:/stubs \
            -p 4770:4770 \
            gripmock-server-local \
            --imports=/protobuf,/googleapis,protogen/proto/types/scalar,protogen/proto/types/specialized-utility,protogen/proto/types/composite-collection,protogen/proto/types/well-known-types,protogen/proto/types/extended-types \
            --stub=/stubs \
            /proto 
          max_wait=60
          waited=0
          until grpcurl -plaintext localhost:4770 list; do
            if [ $waited -ge $max_wait ]; then
              echo "GripMock server failed to start within $max_wait seconds."
              exit 1
            fi
            sleep 1
            waited=$((waited + 1))
          done

      - name: Run examples
        run: |
          ./grpctestify.sh examples/
