name: Integration test
on:
  pull_request:

jobs:
  build:
    name: Run example
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v3

    - name: Docker cache restore
      uses: actions/cache@v4
      with:
        path: /tmp/.docker-cache
        key: docker-cache-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          docker-cache-

    - name: Run Simple Example
      uses: ./
      with:
        entrypoint: example/simple/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run Stream Example
      uses: ./
      with:
        entrypoint: example/stream/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run WKT Example
      uses: ./
      with:
        entrypoint: example/well_known_types/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run Multi Package Example
      uses: ./
      with:
        entrypoint: example/multi-package/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run Multi Files Example
      uses: ./
      with:
        entrypoint: example/multi-files/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run one-of Example
      uses: ./
      with:
        entrypoint: example/one-of/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run stub subfolders example
      uses: ./
      with:
        entrypoint: example/stub-subfolders/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run microservice example
      uses: ./
      with:
        entrypoint: example/ms/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1

    - name: Run microservice example (custom ports)
      uses: ./
      with:
        entrypoint: example/ms/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1
        GRPC_PORT: 5000
        HTTP_PORT: 6000

    - name: Run strict mode example
      uses: ./
      with:
        entrypoint: example/strictmode/entrypoint.sh
        args: |
          --cache-from=type=local,src=/tmp/.docker-cache
          --cache-to=type=local,dest=/tmp/.docker-cache,mode=max
      env:
        DOCKER_BUILDKIT: 1
