name: Integration test
on:
  pull_request:

jobs:
  build:
    name: Run example
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-latest-large
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    - name: Run Simple Example
      uses: ./
      with:
        entrypoint: example/simple/entrypoint.sh
    - name: Run Stream Example
      uses: ./
      with:
        entrypoint: example/stream/entrypoint.sh
    - name: Run WKT Example
      uses: ./
      with:
        entrypoint: example/well_known_types/entrypoint.sh
    - name: Run Multi Package Example
      uses: ./
      with:
        entrypoint: example/multi-package/entrypoint.sh
    - name: Run Multi Files Example
      uses: ./
      with:
        entrypoint: example/multi-files/entrypoint.sh
    - name: Run one-of Example
      uses: ./
      with:
        entrypoint: example/one-of/entrypoint.sh
    - name: Run stub subfolders example
      uses: ./
      with:
        entrypoint: example/stub-subfolders/entrypoint.sh
    - name: Run microservice example
      uses: ./
      with:
        entrypoint: example/ms/entrypoint.sh
    - name: Run microservice example (custom ports)
      uses: ./
      env:
        GRPC_PORT: 5000
        HTTP_PORT: 6000
      with:
        entrypoint: example/ms/entrypoint.sh
