name: GripMock Release

on:
    release:
        types: [created]

jobs:
  releases-matrix:
    permissions:
      contents: write
    name: Release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          # executable_compression: upx -v -9
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md
          ldflags: "-X 'github.com/bavix/gripmock/cmd.version=${{ github.ref_name }}' -s -w"
